# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # NPM
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      
  # Composer
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
